language: php

sudo: false

matrix:
  include:
    - php: 5.4
      env: DB=PGSQL CORE_RELEASE=3.1
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.2
    - php: 5.5
      env: DB=MYSQL CORE_RELEASE=3.3
    - php: 5.6
      env: DB=MYSQL CORE_RELEASE=3.3

before_script:
 - phpenv rehash
 - git clone git://github.com/silverstripe-labs/silverstripe-travis-support.git ~/travis-support
 - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss
 - cd ~/builds/ss

script:
 - phpunit silvershop-api/tests/

branches:
  except:
    - 0.0.1
